### ISSUE TITLE
css not working

### ISSUE THREAD

**Issue by flik** [flukeout/restaurant#116]
I have typed in the css editor: 

p{ margin-top:100px; }

and could not get any result from any where in the page ? http://flukeout.github.io/#

**Comment by flukeout** [comment]
hi @flik - you only have to type the selector, and in the CSS Diner game, there are special elements like ``<plate>`` and ``<bento>``, so if you want to select the ``<plate>`` element (like on the first level) you only have to type in...

``plate`` and press Enter. Let me know if you are still stuck!
