### ISSUE TITLE
Only pass each level if that level's selector is used

### ISSUE THREAD

**Issue by mansisce** [flukeout/restaurant#125]
I am not in favor of this, as this gonna hinder my learning. I was happy to experiment with various solutions for a given level. You should not stop that.

**Comment by flukeout** [comment]
Oh, interesting thank you for the feedback!

**Comment by flukeout** [comment]
One idea would be to allow any valid selector to complete the level, but give a special award like a star for each level where that specific selector is used in the answer. Thoughts?

**Comment by AlanGabbianelli** [comment]
I agree with @mansisce: I think it would be better to leave it as it is, and let people experiment with different solutions. I like the idea of extra points (special award, a star, etc) if the specific selector is used.

**Comment by flukeout** [comment]
Thanks for your feedback! I won't restrict the answers, but will add some kind of bonus indicator if the special selector for that level is used.
