### ISSUE TITLE
Level 21: We have to select odd and not even

### ISSUE THREAD

**Issue by aloisdg** [flukeout/restaurant#142]
Invalid:
```css
plate:even
```

Valid:
```css
plate:odd
```

**Comment by flukeout** [comment]
Is there an error in one of the levels @aloisdg?

**Comment by aloisdg** [comment]
I am not sure if can call that an error.

**Comment by flukeout** [comment]
Oh sorry, I just saw that you mentioned level 21, I'll check it out now.

**Comment by flukeout** [comment]
A couple of things, seems like ``:even`` and ``:odd`` are jQuery selectors, so they work because I'm using jQuery but wouldn't work as plain CSS.

Also the behavior you are seeing is correct, because the first element counts as the ``0`` element, so it considered ``even``.

**Comment by aloisdg** [comment]
ok :)
