### ISSUE TITLE
Really love this

### ISSUE THREAD

**Issue by jmsm16** [flukeout/restaurant#145]
Hello, I have found an issue on your website. It`s not a big deal but i think that you would like to be warned about it. Below I have pasted the problem. 

 `<div class="example"><strong>img[src*="/thumbnails/"]</strong> selects all  image  selements that show images from the "thumbnails" folder.</div>`

Where it is write **image selements**, I think it should be **images** **elements**. It is located at the last level of the game.

**Comment by flukeout** [comment]
Thanks for pointing it out - it looks like it was addressed by @lalov1 in https://github.com/flukeout/css-diner/pull/144 + Glad you're enjoying the project.
