### ISSUE TITLE
Level 23 - can't select a unique apple

### ISSUE THREAD

**Issue by leonsegal** [flukeout/restaurant#165]
there are 3 plates, 2 apples and a pickle:

plate#fancy->apple
plate->apple
plate->pickle

Don't see how to use :only-of-type in this challenge. I solved it using: 
    plate:nth-of-type(2) > apple

**Comment by peygar** [comment]
Isn't there 2 apples on the first plate for this level? I used `plate apple:only-of-type`

**Comment by leonsegal** [comment]
oh are those two apples? It wasn't clear. Thanks for clearing that up.
