### ISSUE TITLE
 I can't pass level 9

### ISSUE THREAD

**Issue by linkchen1982** [flukeout/restaurant#181]
I chose to select:
```css
plate pickle, bento pickle
```
And I saw the shaking animation on those 3 pickles, which usually means I got it, but it just didn't let me pass. What's wrong?

**Comment by ui-coder** [comment]
Just type *plate, bento* - enter ;)

==============
Best regards,
Willie S. Ceres
(@htmlstrap)
------------------------
[image: Picture]

**Comment by linkchen1982** [comment]
Thanks for help!
But I'm just curious I am not wrong if typing in "plate pickle, bento pickle"?

> Just type *plate, bento* - enter ;) ============== Best regards, Willie S. Ceres (@htmlstrap) ------------------------ [image: Picture]

**Comment by ui-coder** [comment]
If "plate pickle, bento pickle" isn't working it surely is wrong. And
again, anything that's not working is wrong! :)


==============
Best regards,
Willie S. Ceres
(@htmlstrap)
------------------------
[image: Picture]

**Comment by tzi** [comment]
@linkchen1982 The pickles you see shaking are shaking because they are a part of the plate or bento. If you look at it, the plate and bento are also shaking.

So when you select the plate, you also select the content of the plate.
But when you select the pickles only, you are not selecting the plates.

**Comment by ui-coder** [comment]
In this particular case, you need to select the ancestor element because it
contains the only element.

==============
Best regards,
Willie S. Ceres
(@htmlstrap)
------------------------
[image: Picture]

**Comment by linkchen1982** [comment]
Thanks for explanation! @ui-coder @tzi 
I didn't realize that Plate and Bento are also shaking.
Now I totally understand!
