### ISSUE TITLE
Lvl 8

### ISSUE THREAD

**Issue by luiznaiper** [flukeout/restaurant#211]
![image](https://user-images.githubusercontent.com/31249948/109748287-3b027c80-7b9e-11eb-8097-ce77d69ce58a.png)

Really lvl 8?

**Comment by meitingshuoguo** [comment]
`bento orange.small` is right.

**Comment by luiznaiper** [comment]
I know, but... i didnt knew i need to put them together without space :/

**Comment by meitingshuoguo** [comment]
![image](https://user-images.githubusercontent.com/16173962/112245232-723ee780-8c8b-11eb-9153-a85575260a15.png)

1. The first one without a space means that the element with class name a in the div is selected (it is found in the div).
2. The second one with a space means that the element with the class name a is selected in all the descendants of the div (it is found in all the descendants of the div).

[Class selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Class_selectors)
[Descendant combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_combinator)
