### ISSUE TITLE
Level 15 First Child Pseudo-selector

### ISSUE THREAD

**Issue by RachelBLondon** [flukeout/restaurant#95]
Having difficulty selecting the first child orange of the second plate div, not sure if this is a bug or my bad!

<div class="table">
<bento></bento>
<plate></plate>
<plate>
<orange/>
<orange/>
<orange/>
</plate>
<pickle class="small"/>
</div>

**Comment by flukeout** [comment]
Thumbs up!

**Comment by Dzovi** [comment]
orange:first

**Comment by AbhinavAdk** [comment]
> Having difficulty selecting the first child orange of the second plate div, not sure if this is a bug or my bad!

try
plate> orange: first-child

**Comment by ThomasMcDonald1** [comment]
If we look at :first-child from the mdn doc on pseudo-classes (https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes), it states that ":first-child Matches an element that is the first of its SIBLINGS.", meaning we do not even need to consider the plate.

So a simpler solution is: orange:first-child

**Comment by massaro2040** [comment]
> If we look at :first-child from the mdn doc on pseudo-classes (https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes), it states that ":first-child Matches an element that is the first of its SIBLINGS.", meaning we do not even need to consider the plate.
> 
> So a simpler solution is: orange:first-child

really thxxxxxxxxx
